title: Shenglai Yin, an ecologist and writer
author: Shenglai Yin  
email: shenglai.yin@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I am a passionate ecologist, specialized in disease ecology, animal movement, global change biology. I also love write,
  planning to publish my articles in this blog. Other tags on me are: meditatior, runner and peace lover.

# social links
twitter_username: Shenglai_Y # DO NOT include the @ character, or else the build will fail!
github_username:  ShenglaiYin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
